import { buildPngWithText } from "@/lib/scan/png";
import { asBlobPart } from "@/lib/bytes";

export async function makeGeminiSample(): Promise<File> {
  const w = 768;
  const h = 512;
  const c = document.createElement("canvas");
  c.width = w;
  c.height = h;
  const ctx = c.getContext("2d");
  if (!ctx) throw new Error("canvas");

  const g = ctx.createLinearGradient(0, 0, 0, h);
  g.addColorStop(0, "#6b8aa3");
  g.addColorStop(0.42, "#c4b49a");
  g.addColorStop(1, "#3e4a3a");
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, w, h);

  ctx.fillStyle = "#e8d7b0";
  ctx.beginPath();
  ctx.arc(560, 118, 54, 0, Math.PI * 2);
  ctx.fill();

  ctx.fillStyle = "#4d5c40";
  hill(ctx, 0, 340, w, 90);
  ctx.fillStyle = "#2f3828";
  hill(ctx, 40, 390, w, 70);

  const img = ctx.getImageData(0, 0, w, h);
  const d = img.data;
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const i = (y * w + x) * 4;
      const lattice = ((x % 8 === 0 ? 4 : 0) + (y % 8 === 0 ? 3 : 0)) * ((x + y) % 2);
      const carrier = 3.2 * Math.sin((x * 0.085 + y * 0.071) * Math.PI) + 2.1 * Math.sin(x * 0.041 + y * 0.053);
      const gn = (y * 13 + x * 7) % 11 === 0 ? 2 : 0;
      d[i] = clamp(d[i] + carrier + lattice * 0.4);
      d[i + 1] = clamp(d[i + 1] + carrier * 1.35 + lattice * 0.5 + gn);
      d[i + 2] = clamp(d[i + 2] + carrier * 0.7);
    }
  }
  ctx.putImageData(img, 0, 0);

  drawSparkle(ctx, w - 36, h - 36);

  const blob = await new Promise<Blob | null>((res) => c.toBlob(res, "image/png"));
  if (!blob) throw new Error("sample encode failed");
  const png = new Uint8Array(await blob.arrayBuffer());
  const tagged = buildPngWithText(png, [
    { key: "Software", value: "Gemini Image · Google DeepMind" },
    { key: "Comment", value: "Generated by Imagen 3 (Gemini). digitalSourceType=trainedAlgorithmicMedia SynthID" },
    { key: "DigitalSourceType", value: "trainedAlgorithmicMedia" },
  ]);
  return new File([asBlobPart(tagged)], "gemini-sample.png", { type: "image/png" });
}

export async function makeDalleSample(): Promise<File> {
  const w = 640;
  const h = 640;
  const c = document.createElement("canvas");
  c.width = w;
  c.height = h;
  const ctx = c.getContext("2d");
  if (!ctx) throw new Error("canvas");
  ctx.fillStyle = "#1c2430";
  ctx.fillRect(0, 0, w, h);
  for (let i = 0; i < 18; i++) {
    ctx.fillStyle = `rgba(220, 210, 190, ${0.04 + (i % 5) * 0.03})`;
    ctx.beginPath();
    ctx.arc(80 + (i * 97) % w, 60 + (i * 131) % h, 40 + (i % 6) * 18, 0, Math.PI * 2);
    ctx.fill();
  }
  ctx.fillStyle = "#e8dfd0";
  ctx.font = "500 28px 'IBM Plex Sans', sans-serif";
  ctx.fillText("claim_generator: OpenAI DALL-E 3", 48, 80);
  ctx.font = "400 16px 'IBM Plex Mono', monospace";
  ctx.fillText("c2pa.created  trainedAlgorithmicMedia", 48, 112);
  const blob = await new Promise<Blob | null>((res) => c.toBlob(res, "image/png"));
  if (!blob) throw new Error("sample encode failed");
  const png = new Uint8Array(await blob.arrayBuffer());
  const tagged = buildPngWithText(png, [
    { key: "Software", value: "OpenAI DALL-E 3" },
    { key: "Comment", value: "claim_generator=ChatGPT-Image c2pa.created digitalSourceType=trainedAlgorithmicMedia" },
  ]);
  return new File([asBlobPart(tagged)], "dalle-sample.png", { type: "image/png" });
}

function hill(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, amp: number) {
  ctx.beginPath();
  ctx.moveTo(x, y + amp);
  for (let i = 0; i <= w; i += 8) {
    const yy = y + Math.sin(i * 0.01 + x) * amp * 0.35 + Math.sin(i * 0.023) * amp * 0.2;
    ctx.lineTo(x + i, yy);
  }
  ctx.lineTo(x + w, y + amp + 80);
  ctx.lineTo(x, y + amp + 80);
  ctx.closePath();
  ctx.fill();
}

function drawSparkle(ctx: CanvasRenderingContext2D, cx: number, cy: number) {
  ctx.save();
  ctx.translate(cx, cy);
  ctx.fillStyle = "#7ad0c4";
  star(ctx, 0, 0, 4, 11, 4.2);
  ctx.fillStyle = "#f0eee6";
  star(ctx, 0, 0, 4, 5.5, 2);
  ctx.restore();
}

function star(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  n: number,
  outer: number,
  inner: number,
) {
  ctx.beginPath();
  for (let i = 0; i < n * 2; i++) {
    const r = i % 2 === 0 ? outer : inner;
    const a = (i * Math.PI) / n - Math.PI / 2;
    const fn = i === 0 ? ctx.moveTo.bind(ctx) : ctx.lineTo.bind(ctx);
    fn(x + Math.cos(a) * r, y + Math.sin(a) * r);
  }
  ctx.closePath();
  ctx.fill();
}

function clamp(v: number): number {
  return v < 0 ? 0 : v > 255 ? 255 : v | 0;
}
